apiVersion: v1
kind: Service
metadata:
  labels:
    service: udgram-backend-feed
  name: udgram-backend-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: udgram-backend-feed