branches:
  only:
    - main
language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "no install needed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed beshosmile/udagram-api-feed
  - docker tag udagram-api-user beshosmile/udagram-api-user
  - docker tag reverseproxy beshosmile/reverseproxy
  - docker tag udagram-frontend beshosmile/udagram-frontend:v11

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push beshosmile/udagram-api-feed
  - docker push beshosmile/udagram-api-user
  - docker push beshosmile/reverseproxy
  - docker push beshosmile/udagram-frontend:v11