apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-feed
  labels:
    service: frontend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend-feed
  template:
    metadata:
      labels:
        service: frontend-feed
        api: external
    spec:
      containers:
      - name: frontend-feed
        image: beshosmile/udagram-frontend
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2024Mi"
            cpu: "250m"
          limits:
            memory: "4024Mi"
            cpu: "500m"   
        ports:
        - containerPort: 80
      restartPolicy: Always