apiVersion: v1
kind: Service
metadata:
  labels:
    service: udgram-frontend
  name: udgram-frontend
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
  selector:
    service: udgram-frontend