apiVersion: apps/v1
kind: Deployment
metadata:
  name: udgram-frontend
  labels:
    service: udgram-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udgram-frontend
  template:
    metadata:
      labels:
        service: udgram-frontend
        api: external
    spec:
      containers:
      - name: udgram-frontend
        image: beshosmil/udagram-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      restartPolicy: Always